baseURL = "http://www.bckmn.dev/"
theme = "LoveIt"
title = "Marvin Beckmann"

languageCode = "en"
languageName = "English"

# Author config
[author]
  name = "Marvin Beckmann"
  email = ""
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 2
    identifier = "posts"
    pre = ""
    post = ""
    name = "blog"
    url = "/posts/"
    title = ""
  [[menu.main]]
    weight = 1
    identifier = "about_me"
    pre = ""
    post = ""
    name = "about_me"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "resume"
    pre = ""
    post = ""
    name = "resume"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "skillset"
    pre = ""
    post = ""
    name = "skillset"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 10
    identifier = "impressum"
    pre = ""
    post = ""
    name = "impressum"
    url = "/categories/"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params.home]
  [params.home.profile]
    enable = true
    avatarURL = "/images/profile.png"
    subtitle = "A Clean, Elegant but Advanced Hugo Theme"
    typeit = true
    social = true
    disclaimer = ""
  [params.home.posts]
    enable = false
    paginate = 6

[params.social]
  [params.social.Mastodon]
    weight = 3
    id = "@xxxx"
    prefix = "https://mastodon.social/"
    title = "Mastodon"
  [params.social.Instagram]
    weight = 2
    id = "@xxxx"
    prefix = "https://mastodon.social/"
    title = "Mastodon"
  [params.social.Linkedin]
    weight = 1
    id = "@xxxx"
    prefix = "https://mastodon.social/"
    title = "Mastodon"
  [params.social.Email]
    weight = 1
    id = "@xxxx"
    prefix = "https://mastodon.social/"
    title = "Mastodon"
  [params.social.Discord]
    weight = 1
    id = "@xxxx"
    prefix = "https://mastodon.social/"
    title = "Mastodon"
  [params.social.Threema]
    weight = 1
    id = "@xxxx"
    prefix = "https://mastodon.social/"
    title = "Mastodon"

 # TypeIt config
[params.typeit]
  speed = 100
  cursorSpeed = 1000
  cursorChar = "|"
  duration = -1
