baseurl = "http://www.bckmn.dev"
title = "~/marvin_beckmann $ "
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Marvin Beckmann"
  info = "Full Stack DevOps and Magician"
  description = ""
  keywords = "blog,developer,personal"
  avatarurl = "images/marvin_bw.jpg"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Mail"
  icon = "fa fa-mail fa-2x"
  weight = 1
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/johndoe/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 3
  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Discord"
  icon = "fa fa-discord fa-2x"
  weight = 4
  url = "https://twitter.com/johndoe/"


[[menu.main]]
  identifier = "blog"
  name       = "blog"
  url        = "/posts"
  weight     = 1
[[menu.main]]
  identifier = "impressum"
  name       = "impressum"
  url        = "/posts"
  weight     = 5
[[menu.main]]
  identifier = "resume"
  name       = "resume"
  url        = "/posts"
  weight     = 4
[[menu.main]]
  identifier = "skillset"
  name       = "skillset"
  url        = "/posts"
  weight     = 3
[[menu.main]]
  identifier = "about_me"
  name       = "about_me"
  url        = "/posts"
  weight     = 2